### ISSUE TITLE
Intercept Proxy Edge Case

### ISSUE THREAD

**Issue by bhendo** [bdwyertech/gontlm-proxy#1]
Thanks for staring my repo!

I just want to give you a heads up about an edge case where the solution you created may not work (and ultimately the reason why I created https://github.com/bhendo/concord) 

https://github.com/golang/go/issues/20053#issuecomment-331982312

Cheers!

**Comment by bdwyertech** [comment]
Thanks @bhendo , I've got it on the To-Do list to figure out how to integrate your solution with goproxy -- spent a little time experimenting locally and couldnt figure a way to pass/inject the RoundTripper into goproxy.

it seems right now the solution I've hacked together works great until it hits a Google site ( thinking SPDY/TLS related, something with a 200 resp code and empty body)

**Comment by bdwyertech** [comment]
Think I figured it out... Thanks @bhendo 

https://github.com/bdwyertech/gontlm-proxy/commit/a90ccd83332624dccd696d184a5693d84319e541

Now if I can figure out how to hijack and preserved the upstream SSL cert instead of MITM'ing...

**Comment by bhendo** [comment]
Very cool, glad that worked out. Do sites that didn't work previously work now?

**Comment by bdwyertech** [comment]
Yep, sites that didn't previously work now do!
